spring:
  application:
    name: ai-service
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-7-sonnet-latest
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            server:
              stdio: false
              url: http://localhost:8081
              sse-endpoint: /sse
              sse-message-endpoint: /mcp/messages

server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    service-url:
       defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
