spring:
  application:
    name: mcp-service
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:./mcp-servers-config.json
        sse:
          connections:
            ecommerce:
              stdio: false
              url: http://localhost:8081
              sse-endpoint: /sse
              sse-message-endpoint: /mcp/messages

server:
  port: 8001

serverless-service:
  base-url: http://serverless-service
ai-service:
  base-url: http://ai-service

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      serverlessCB:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        failureRateThreshold: 25
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

      filesystemCB:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        failureRateThreshold: 25
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

      ecommerceCB:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        failureRateThreshold: 25
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

      aiCB:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        failureRateThreshold: 25
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
